fn main() {
    // parser.c is generated by `tree-sitter generate` (pinned CLI, see
    // grammar/) and checked in — consumers never need the CLI.
    let src = std::path::Path::new("grammar/src");
    let mut build = cc::Build::new();
    build.include(src).file(src.join("parser.c")).warnings(false);
    build.compile("tree-sitter-duckdb");
    println!("cargo:rerun-if-changed=grammar/src/parser.c");
}
