#!/usr/bin/env python3
"""Regenerate crates/harbor/src/engine_fill.rs from libduckdb-sys.

The loadable-extension bindings route every DuckDB C call through an
AtomicPtr filled from a `duckdb_ext_api_v1` struct. This script reads
that struct's field list out of the exact crate version Cargo resolved
and emits the dlsym loop that fills it — field names ARE the exported C
symbol names, and generating from the same bindings file means the two
can never drift.

Run after bumping the duckdb crate:  python3 scripts/gen-engine-fill.py
"""

import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "crates/harbor/src/engine_fill.rs")

# The resolved libduckdb-sys version, straight from Cargo.lock.
lock = open(os.path.join(ROOT, "Cargo.lock")).read()
m = re.search(r'name = "libduckdb-sys"\nversion = "([^"]+)"', lock)
version = m.group(1) if m else None
if not version:
    sys.exit("libduckdb-sys not found in Cargo.lock")
candidates = glob.glob(os.path.expanduser(
    f"~/.cargo/registry/src/*/libduckdb-sys-{version}/src/bindgen_bundled_version_loadable.rs"))
if not candidates:
    sys.exit(f"libduckdb-sys-{version} loadable bindings not found in ~/.cargo/registry")
bindings = candidates[0]

src = open(bindings).read()
start = src.index("pub struct duckdb_ext_api_v1 {")
depth, i = 0, start
while True:
    if src[i] == "{":
        depth += 1
    elif src[i] == "}":
        depth -= 1
        if depth == 0:
            break
    i += 1
body = src[start:i]

fields = re.findall(r"pub (duckdb_\w+):", body)
if len(fields) < 400:
    sys.exit(f"only {len(fields)} fields parsed — bindings format changed?")

with open(OUT, "w") as f:
    f.write(f"""\
// Generated by scripts/gen-engine-fill.py from libduckdb-sys {version} —
// do not edit. Field names in duckdb_ext_api_v1 are the exported C
// symbol names; regenerating from the resolved crate keeps them in
// lockstep with the wrappers that will consume the struct.

use duckdb::ffi::duckdb_ext_api_v1;
use libloading::Library;

/// Fill `api` from `lib`, one dlsym per field. Missing symbols stay
/// `None` — the generated init tolerates gaps, and a call through a gap
/// asserts with a clear message. Returns how many symbols resolved.
pub(crate) unsafe fn fill(lib: &Library, api: &mut duckdb_ext_api_v1) -> usize {{
    let mut n = 0usize;
    macro_rules! f {{
        ($field:ident, $name:literal) => {{
            if let Ok(s) = unsafe {{ lib.get::<unsafe extern "C" fn()>($name) }} {{
                api.$field = Some(unsafe {{ std::mem::transmute(*s) }});
                n += 1;
            }}
        }};
    }}
""")
    for name in fields:
        f.write(f'    f!({name}, b"{name}\\0");\n')
    f.write("    n\n}\n")

print(f"engine_fill.rs: {len(fields)} symbols from libduckdb-sys {version}")
