#!/usr/bin/env ruby
# Regenerate crates/harbor/src/v2/ffi.rs from DuckDB's v2 C API spec.
#
# The spec (api_spec/v2/**/*.yaml in the duckdb repo) is the same machine-
# readable source DuckDB's own capigen compiles duckdb_v2.h from: handles,
# structs, enums, callbacks, aliases, and 307 functions with per-parameter
# type/indirection/const/ownership. Generating our FFI from it — rather than
# transcribing the header — means the bindings can never drift from the
# engine, and a spec bump is one re-run away.
#
# Run after moving the engine pin:  ruby scripts/gen-v2-ffi.rb [path/to/api_spec/v2]

require "yaml"

ROOT = File.expand_path("..", __dir__)
SPEC = ARGV[0] || ENV["DUCKDB_API_SPEC"] || File.expand_path("../duckdb/api_spec/v2", ROOT)
OUT  = File.join(ROOT, "crates/harbor/src/v2/ffi.rs")

abort "spec not found: #{SPEC}" unless File.exist?(File.join(SPEC, "metadata.yaml"))

meta   = YAML.safe_load_file(File.join(SPEC, "metadata.yaml"))
PREFIX = meta["prefix"] # "duckdb_v2_"

# options/ holds capigen's C-header emission config, not API surface.
files = Dir[File.join(SPEC, "**/*.yaml")].sort - [File.join(SPEC, "metadata.yaml")]
files.reject! { |f| f.include?("/options/") }

# ---------------------------------------------------------------------------
# Collect the whole surface first; Rust items may reference in any order, but
# the type mapper needs the full name->category table before emitting.
# ---------------------------------------------------------------------------
handles, structs, enums, callbacks, aliases, constants = {}, {}, {}, {}, {}, {}
modules = [] # [name, functions(ordered)]

files.each do |f|
  y = YAML.safe_load_file(f)
  next unless y.is_a?(Hash)
  (y["handles"] || {}).each { |n, h| handles[n] = h if h.is_a?(Hash) || h.nil? }
  (y["structs"] || {}).each { |n, s| structs[n] = s }
  (y["enums"] || {}).each { |n, e| enums[n] = e }
  (y["callbacks"] || {}).each { |n, c| callbacks[n] = c }
  (y["aliases"] || {}).each { |n, a| aliases[n] = a }
  (y["constants"] || {}).each { |n, c| constants[n] = c }
  fns = y["functions"] || {}
  modules << [y["module"] || File.basename(f, ".yaml"), fns] unless fns.empty?
end

PRIMS = {
  "void" => "c_void", "char" => "c_char", "bool" => "bool",
  "i8" => "i8", "i16" => "i16", "i32" => "i32", "i64" => "i64",
  "u8" => "u8", "u16" => "u16", "u32" => "u32", "u64" => "u64",
  "f32" => "f32", "f64" => "f64", "idx" => "idx_t", "size" => "usize",
  # Declared as primitives in metadata.yaml; opaque types on our side.
  "extension" => "extension_handle",
  "ArrowSchema" => "ArrowSchema", "ArrowArray" => "ArrowArray",
  "ArrowArrayStream" => "ArrowArrayStream",
}
ARROW = %w[ArrowSchema ArrowArray ArrowArrayStream]

RUST_KEYWORDS = %w[as box break const continue crate dyn else enum extern false fn
  for if impl in let loop match mod move mut pub ref return self static struct
  super trait true type unsafe use where while async await try].freeze

def ident(name)
  RUST_KEYWORDS.include?(name) ? "#{name}_" : name
end

# Spec struct/alias names become Rust types with a uniform `_t` suffix (the
# C header's alias convention), which also dodges the `str` keyword.
def tname(name)
  name.end_with?("_t") ? name : "#{name}_t"
end

# Map a spec type reference to Rust, honoring indirection and const. C's
# `const T *` binds const innermost, so const applies at the first star.
def rust_type(type, indirection, is_const)
  base =
    if PRIMS.key?(type)          then PRIMS[type]
    elsif HANDLES.include?(type) then "#{type}_handle"
    elsif ENUMS.include?(type)   then type
    elsif CALLBACKS.include?(type) then "#{type}_fn"
    elsif STRUCTS.include?(type) || ALIASES.include?(type) then tname(type)
    else abort "unknown type in spec: #{type.inspect}"
    end
  return base if indirection.zero?
  stars = [is_const ? "*const " : "*mut "] + ["*mut "] * (indirection - 1)
  stars.reverse.join + base
end

def param_type(p)
  rust_type(p["type"], p["indirection"] || 0, p["const"] || false)
end

# One-line doc: first line of the spec description, if any.
def doc(text, indent = "")
  line = text.to_s.lines.first.to_s.strip
  line.empty? ? "" : "#{indent}/// #{line}\n"
end

HANDLES   = handles.keys
ENUMS     = enums.keys
STRUCTS   = structs.keys
CALLBACKS = callbacks.keys
ALIASES   = aliases.keys

out = +""
out << <<~RS
  // Generated by scripts/gen-v2-ffi.rb from DuckDB api_spec/v2 — do not edit.
  //
  // The v2 C API surface: #{handles.size} handles, #{enums.size} enums, #{structs.size} structs,
  // #{callbacks.size} callbacks, and #{modules.sum { |_, fns| fns.size }} functions, every one returning ERROR with an
  // optional trailing *mut error_info_handle out-param. `Api` is the dlsym-
  // filled function table; symbol names are `#{PREFIX}` + field name.
  #![allow(non_camel_case_types, non_snake_case, dead_code)]

  use std::ffi::{c_char, c_void};
  use libloading::Library;

  pub type idx_t = u64;

RS

# --- handles ---------------------------------------------------------------
out << "// --- handles: distinct opaque pointer types --------------------------------\n\n"
(HANDLES + ["extension"]).sort.each do |n|
  out << doc(handles.dig(n, "description"))
  out << "#[repr(C)]\npub struct _#{n} {\n    _opaque: [u8; 0],\n}\npub type #{n}_handle = *mut _#{n};\n\n"
end
ARROW.each do |n|
  out << "/// Arrow C Data Interface struct; crossed only by pointer here.\n"
  out << "#[repr(C)]\npub struct #{n} {\n    _opaque: [u8; 0],\n}\n\n"
end

# --- constants -------------------------------------------------------------
constants.each do |n, c|
  out << doc(c["description"])
  out << "pub const #{n}: usize = #{c["value"]};\n\n"
end

# --- enums -----------------------------------------------------------------
out << "// --- enums: newtype-free i32 constants (unknown values stay representable) -\n\n"
enums.each do |n, e|
  out << doc(e["description"])
  out << "pub type #{n} = i32;\n"
  next_value = 0 # C enum rule: a value-less entry is previous + 1
  e["values"].each do |vn, v|
    value = v["value"] || next_value
    next_value = value + 1
    out << doc(v["description"])
    out << "pub const #{vn}: #{n} = #{value};\n"
  end
  out << "\n"
end

# --- callbacks -------------------------------------------------------------
out << "// --- callbacks -------------------------------------------------------------\n\n"
callbacks.each do |n, c|
  params = (c["parameters"] || {}).map { |pn, p| "#{ident(pn)}: #{param_type(p)}" }
  ret = c["return_type"]
  ret_s =
    if ret == "void" && (c["return_pointer"] || 0).zero? then ""
    else " -> #{rust_type(ret, c["return_pointer"] || 0, c["return_const"] || false)}"
    end
  out << doc(c["description"])
  out << "pub type #{n}_fn = Option<unsafe extern \"C\" fn(#{params.join(", ")})#{ret_s}>;\n\n"
end

# --- structs ---------------------------------------------------------------
out << "// --- structs (all repr(C), crossed by value where the spec says so) --------\n\n"

def emit_fields(out, fields, owner)
  fields.each do |fld|
    if fld["union"]
      # Emit member structs then the union itself; union fields must be Copy.
      fld["union"].each do |m|
        out << "#[repr(C)]\n#[derive(Clone, Copy)]\npub struct #{owner}_#{m["name"]}_t {\n"
        m["fields"].each { |mf| out << "    pub #{ident(mf["name"])}: #{field_type(mf)},\n" }
        out << "}\n\n"
      end
      out << "#[repr(C)]\n#[derive(Clone, Copy)]\npub union #{owner}_#{fld["name"]}_u {\n"
      fld["union"].each { |m| out << "    pub #{ident(m["name"])}: #{owner}_#{m["name"]}_t,\n" }
      out << "}\n\n"
    end
  end
  out << "#[repr(C)]\n#[derive(Clone, Copy)]\npub struct #{tname(owner)} {\n"
  fields.each do |fld|
    ty = fld["union"] ? "#{owner}_#{fld["name"]}_u" : field_type(fld)
    out << doc(fld["description"], "    ")
    out << "    pub #{ident(fld["name"])}: #{ty},\n"
  end
  out << "}\n\n"
end

def field_type(fld)
  base = rust_type(fld["type"], fld["pointer"] || 0, fld["const"] || false)
  fld["array_size"] ? "[#{base}; #{fld["array_size"]}]" : base
end

structs.each do |n, s|
  out << doc(s["description"])
  emit_fields(out, s["fields"], n)
end

# --- aliases ---------------------------------------------------------------
out << "// --- aliases ---------------------------------------------------------------\n\n"
aliases.each do |n, a|
  out << doc(a["description"])
  out << "pub type #{tname(n)} = #{rust_type(a["underlying"], 0, false)};\n\n"
end

# --- the function table ----------------------------------------------------
all_fns = [] # [name, sig]
out << "// --- the function table ----------------------------------------------------\n\n"
out << "/// Every v2 entry point, resolved by name from the loaded engine. A field is\n"
out << "/// `None` when the engine predates that symbol; callers unwrap with context.\n"
out << "///\n"
out << "/// repr(C) is load-bearing: `fill` writes the table as consecutive\n"
out << "/// pointer-sized slots in declaration order, matching `SYMBOL_NAMES`.\n"
out << "#[repr(C)]\npub struct Api {\n"
modules.each do |mod_name, fns|
  out << "    // -- #{mod_name}\n"
  fns.each do |name, fn|
    params = (fn["parameters"] || {}).map { |pn, p| "#{ident(pn)}: #{param_type(p)}" }
    sig = "unsafe extern \"C\" fn(#{params.join(", ")}) -> #{fn["return_type"]}"
    out << doc(fn["description"], "    ")
    out << "    pub #{name}: Option<#{sig}>,\n"
    all_fns << name
  end
end
out << "}\n\n"

out << "/// The exported C symbol names, in `Api` field (declaration) order.\n"
out << "const SYMBOL_NAMES: [&[u8]; #{all_fns.size}] = [\n"
all_fns.each { |name| out << "    b\"#{PREFIX}#{name}\\0\",\n" }
out << "];\n\n"
out << <<~RS
  impl Api {
      /// Resolve every symbol from `lib`. Missing ones stay `None`; the count
      /// of hits comes back so the loader can tell "no v2 API" from "older v2".
      ///
      /// Data-driven on purpose: one loop over SYMBOL_NAMES instead of #{all_fns.size}
      /// inlined lookups — the straight-line version was the largest symbol in
      /// the whole binary. Sound because Api is repr(C) and every field is an
      /// `Option` of an `extern "C" fn` pointer: #{all_fns.size} consecutive slots, each
      /// pointer-sized with the null niche, in exactly SYMBOL_NAMES order.
      pub unsafe fn fill(lib: &Library) -> (Api, usize) {
          // All-zero bytes is `None` for every `Option<extern "C" fn>` field.
          let mut api: Api = unsafe { std::mem::zeroed() };
          let slots = &mut api as *mut Api as *mut Option<unsafe extern "C" fn()>;
          let mut n = 0usize;
          for (i, name) in SYMBOL_NAMES.iter().enumerate() {
              if let Ok(s) = unsafe { lib.get::<unsafe extern "C" fn()>(name) } {
                  unsafe { *slots.add(i) = Some(*s) };
                  n += 1;
              }
          }
          (api, n)
      }
  }
RS

File.write(OUT, out)
puts "ffi.rs: #{all_fns.size} functions, #{handles.size} handles, #{enums.size} enums, " \
     "#{structs.size} structs, #{callbacks.size} callbacks — #{out.lines.size} lines"
